export default {
  SET_ACTIVE_AOS: 'SET_ACTIVE_AlGO_ORDERS',
  HANDLE_ACTIVE_AOS: 'HANDLE_ACTIVE_AlGO_ORDERS',
  SHOW_ACTIVE_AOS_MODAL: 'SHOW_ACTIVE_AlGO_ORDERS_MODAL',
  GET_AO_PARAMS: 'GET_AO_PARAMS',
  SET_AO_PARAMS: 'SET_AO_PARAMS',
  APPEND_AO_PARAMS: 'APPEND_AO_PARAMS',
  REMOVE_AO_PARAMS: 'REMOVE_AO_PARAMS',
  SAVE_AO_PARAMS: 'SAVE_AO_PARAMS',
  SET_ACTIVE_AO_PARAMS_ID: 'SET_ACTIVE_AO_PARAMS_ID',
  SHOW_AOS_HISTORY: 'SHOW_AOS_HISTORY',
}
