export const FETCH_AUTH_TOKEN = 'AUTH_TOKEN/FETCH_AUTH_TOKEN'
export const FETCH_AUTH_TOKEN_SUCCESS = 'AUTH_TOKEN/FETCH_AUTH_TOKEN_SUCCESS'
export const FETCH_AUTH_TOKEN_ATTEMPTED = 'AUTH_TOKEN/FETCH_AUTH_TOKEN_ATTEMPTED'
export const FETCH_AUTH_TOKEN_FAIL = 'AUTH_TOKEN/FETCH_AUTH_TOKEN_FAIL'
export const SET_AUTH_TOKEN_INVALID = 'AUTH_TOKEN/SET_AUTH_TOKEN_INVALID'
export const AUTH_TOKEN_REFRESH_INTERVAL = 60 * 1000 // 60 seconds
