export const UI_MODAL_KEYS = {
  OLD_FORMAT_MODAL: 'OldFormatModal',
  AO_PAUSE_MODAL: 'AOPauseModal',
  APP_SETTINGS_MODAL: 'AppSettingsModal',
  CCY_INFO_MODAL: 'CcyInfoModal',
  CONFIRM_DMS_MODAL: 'ConfirmDMSModal',
  EDIT_ORDER_MODAL: 'EditOrderModal',
  RELAUNCH_ORDER_MODAL: 'RelaunchOrderModal',
  CLOSE_POSITION_MODAL: 'ClosePositionModal',
  NO_CONNECTION_MODAL: 'NoConnectionModal',
  NOTIFICATIONS_PANEL: 'NotificationsPanel',
  REFILL_BALANCE_MODAL: 'RefillBalanceModal',
  CLOSE_SESSION_MODAL: 'CloseSessionModal',
  RESET_LIVE_API_KEY_MODAL: 'ResetLiveApiKeyModal',
  RESET_PAPER_API_KEY_MODAL: 'ResetPaperApiKeyModal',
  HELP_US_IMPROVE_HONEY_MODAL: 'HelpUsImproveHoneyModal',
  BAD_INTERNET_CONNECTION_MODAL: 'BadInternetConnectionModal',
}
