module.exports = {
  SET_UI_VALUE: 'UI_SET_UI_VALUE',
  UPDATE_UI_VALUE: 'UI_UPDATE_UI_VALUE',
  SAVE_COMPONENT_STATE: 'UI_SAVE_COMPONENT_STATE',
  UPDATE_COMPONENT_STATE: 'UI_UPDATE_COMPONENT_STATE',
  SAVE_LAYOUT: 'UI_SAVE_LAYOUT',
  CREATE_LAYOUT: 'UI_CREATE_LAYOUT',
  DELETE_LAYOUT: 'UI_DELETE_LAYOUT',

  ADD_COMPONENT: 'UI_ADD_COMPONENT',
  REMOVE_COMPONENT: 'UI_REMOVE_COMPONENT',
  CHANGE_LAYOUT: 'UI_CHANGE_LAYOUT',
  SELECT_LAYOUT: 'UI_SELECT_LAYOUT',

  SET_ACTIVE_MARKET: 'SET_SAVE_MARKET',
  SET_ACTIVE_EXCHANGE: 'UI_SET_ACTIVE_EXCHANGE',

  SAVE_SETTINGS: 'SAVE_SETTINGS',

  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
  REMOVE_NOTIFICATIONS: 'REMOVE_NOTIFICATIONS',
  CLEAR_NOTIFICATIONS: 'CLEAR_NOTIFICATIONS',

  TRADING_PAGE: 'TRADING_TERMINAL',
  MARKET_PAGE: 'MARKET_DATA',
  STRATEGY_PAGE: 'STRATEGY_EDITOR',
  SETTINGS_PAGE: 'SETTINGS',

  DATA_NOTIFICATION: 'UI_DATA_NOTIFICATION',
  SET_CURRENT_STRATEGY: 'UI_SET_CURRENT_STRATEGY',
  SET_IS_STRATEGY_DIRTY: 'UI_SET_IS_STRATEGY_DIRTY',

  SET_TRADING_MODE: 'SET_TRADING_MODE',
  SET_MARKET_FROM_STORE: 'SET_MARKET_FROM_STORE',
  CHANGE_TICKERS_VOLUME_UNIT: 'UI_CHANGE_TICKERS_VOLUME_UNIT',
  SET_SETTINGS_TAB: 'UI_SET_SETTINGS_TAB',
  SET_STRATEGY_TAB: 'SET_STRATEGY_TAB',
  UPDATE_SERVICE_STATUS: 'UI_UPDATE_SERVICE_STATUS',
  CHANGE_MODE: 'UI_CHANGE_MODE',
  CHANGE_UI_MODAL_STATE: 'UI_CHANGE_UI_MODAL_STATE',
  TOGGLE_UI_MODAL_STATE: 'UI_TOGGLE_UI_MODAL_STATE',

  REMOVE_STRATEGY: 'UI_REMOVE_STRATEGY',
}
