module.exports = {
  SET_UI_VALUE: 'UI_SET_UI_VALUE',
  UPDATE_UI_VALUE: 'UI_UPDATE_UI_VALUE',
  SAVE_REMOTE_VERSION: 'SAVE_REMOTE_VERSION',
  SAVE_COMPONENT_STATE: 'UI_SAVE_COMPONENT_STATE',
  UPDATE_COMPONENT_STATE: 'UI_UPDATE_COMPONENT_STATE',
  SAVE_LAYOUT: 'UI_SAVE_LAYOUT',
  STORE_UNSAVED_LAYOUT: 'UI_STORE_UNSAVED_LAYOUT',
  CREATE_LAYOUT: 'UI_CREATE_LAYOUT',
  DELETE_LAYOUT: 'UI_DELETE_LAYOUT',

  SET_LAYOUT_ID: 'UI_SET_LAYOUT_ID',
  ADD_COMPONENT: 'UI_ADD_COMPONENT',
  REMOVE_COMPONENT: 'UI_REMOVE_COMPONENT',
  CHANGE_LAYOUT: 'UI_CHANGE_LAYOUT',
  SELECT_LAYOUT: 'UI_SELECT_LAYOUT',

  SET_ACTIVE_MARKET: 'SET_SAVE_MARKET',
  SET_ACTIVE_EXCHANGE: 'UI_SET_ACTIVE_EXCHANGE',

  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  SAVE_SETTINGS: 'SAVE_SETTINGS',

  RECEIVE_CORE_SETTINGS: 'RECEIVE_CORE_SETTINGS',

  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
  REMOVE_NOTIFICATIONS: 'REMOVE_NOTIFICATIONS',
  CLEAR_NOTIFICATIONS: 'CLEAR_NOTIFICATIONS',

  TRADING_PAGE: 'TRADING_TERMINAL',
  MARKET_PAGE: 'MARKET_DATA',
  STRATEGY_PAGE: 'STRATEGY_EDITOR',
  SETTINGS_PAGE: 'SETTINGS',

  FINISH_GUIDE: 'FINISH_GUIDE',

  DATA_NOTIFICATION: 'UI_DATA_NOTIFICATION',
  SET_STRATEGY_EXECUTION_ID: 'SET_STRATEGY_EXECUTION_ID',

  SET_TRADING_MODE: 'SET_TRADING_MODE',
  SET_MARKET_FROM_STORE: 'SET_MARKET_FROM_STORE',
  CHANGE_EDIT_ORDER_MODAL_DATA: 'UI_CHANGE_EDIT_ORDER_MODAL_DATA',
  CHANGE_TICKERS_VOLUME_UNIT: 'UI_CHANGE_TICKERS_VOLUME_UNIT',
  CHANGE_CLOSE_POSITION_MODAL_DATA: 'UI_CHANGE_CLOSE_POSITION_MODAL_DATA',
  SET_SETTINGS_TAB: 'UI_SET_SETTINGS_TAB',
  SET_FEATURE_FLAGS: 'UI_SET_FEATURE_FLAGS',
  SET_STRATEGY_TAB: 'SET_STRATEGY_TAB',
  UPDATE_SERVICE_STATUS: 'UI_UPDATE_SERVICE_STATUS',
  CHANGE_MODE: 'UI_CHANGE_MODE',
  CHANGE_UI_MODAL_STATE: 'UI_CHANGE_UI_MODAL_STATE',
  TOGGLE_UI_MODAL_STATE: 'UI_TOGGLE_UI_MODAL_STATE',
}
