export const UI_KEYS = {
  isBadInternetConnection: 'isBadInternetConnection',
  isLoadingOrderHistData: 'isLoadingOrderHistData',
  isOrderExecuting: 'isOrderExecuting',
  pendingLiveStrategy: 'pendingLiveStrategy',
  currentStrategy: 'currentStrategy',
  isStrategyDirty: 'isStrategyDirty',
  layoutID: 'layoutID',
  orderToEdit: 'orderToEdit',
  closePositionModalData: 'closePositionModalData',
  featureFlags: 'featureFlags',
  coreSettings: 'coreSettings',
  settings: 'settings',
  unsavedLayout: 'unsavedLayout',
  remoteVersion: 'remoteVersion',
  isApplicationHidden: 'isApplicationHidden',
}
