name: Pull request verify workflow

on:
  # Trigger the workflow on push or pull request,
  # but only for the default(main) branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, labeled, synchronize, ready_for_review]

jobs:
  checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Run Build Check
        run: npm run build

      - name: Run Lint Check
        run: npm run lint

      - name: Annotate Checks
        uses: agyemanjp/ci-checks-action@2.0.3
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          checks: '[
            {
              "name": "build",
              "fileName": ".build-report.json",
              "prChangesOnly": true
            },
            {
              "name": "lint",
              "fileName": ".lint-report.json",
              "prChangesOnly": true
            }
          ]'
